"""The five fleet agents, mirrored from agents/defs/*.yaml so the cards exist before anyone reports."""
from __future__ import annotations

AUTHORITY_CHIPS = ["can_write_code", "can_review", "can_merge", "can_deploy", "can_change_business_rules"]

FLEET: list[dict] = [
    {
        "handle": "scout",
        "display_name": "Scout",
        "avatar": "🔭",
        "color": "#f59e0b",
        "remit": "Watches the production error queue, clusters errors into incidents, and opens well-written bug tickets.",
        "mode": "autonomous",
        "authority": {
            "can_read_production_telemetry": True,
            "can_create_tickets": True,
            "can_write_code": False,
            "can_review": False,
            "can_merge": False,
            "can_deploy": False,
            "can_change_business_rules": False,
            "must_escalate_when": ["security_impact", "customer_impact_over_500"],
        },
    },
    {
        "handle": "forge",
        "display_name": "Forge",
        "avatar": "⚒️",
        "color": "#3b82f6",
        "remit": "Picks up bug tickets, reproduces them with a failing test, fixes them, and opens a pull request.",
        "mode": "autonomous",
        "authority": {
            "can_read_production_telemetry": True,
            "can_create_tickets": False,
            "can_write_code": True,
            "can_open_pull_requests": True,
            "can_review": False,
            "can_merge": False,
            "can_deploy": False,
            "can_change_business_rules": False,
            "can_change_schema": False,
            "must_escalate_when": [
                "ambiguous_requirement",
                "business_rule_change",
                "security_impact",
                "data_migration",
                "cost_over_threshold",
            ],
        },
    },
    {
        "handle": "sentinel",
        "display_name": "Sentinel",
        "avatar": "🛡️",
        "color": "#a855f7",
        "remit": "Reviews Forge's pull requests independently for correctness, test quality, scope and security.",
        "mode": "autonomous",
        "authority": {
            "can_read_production_telemetry": False,
            "can_create_tickets": False,
            "can_write_code": False,
            "can_review": True,
            "can_request_changes": True,
            "can_approve": False,
            "can_merge": False,
            "can_deploy": False,
            "can_change_business_rules": False,
            "must_escalate_when": ["security_impact"],
        },
    },
    {
        "handle": "conductor",
        "display_name": "Conductor",
        "avatar": "🎼",
        "color": "#10b981",
        "remit": "After a human merges, watches the deploy, smoke-checks production, confirms the error is gone, and closes the ticket.",
        "mode": "autonomous",
        "authority": {
            "can_read_production_telemetry": True,
            "can_create_tickets": False,
            "can_write_code": False,
            "can_review": False,
            "can_merge": False,
            "can_deploy": True,
            "can_close_tickets": True,
            "can_reopen_tickets": True,
            "can_change_business_rules": False,
            "must_escalate_when": ["verification_failed", "rollback_needed"],
        },
    },
    {
        "handle": "watchtower",
        "display_name": "Watchtower",
        "avatar": "🗼",
        "color": "#ef4444",
        "remit": "When the error rate crosses a threshold, opens an incident, keeps a running timeline, and drafts a blameless postmortem.",
        "mode": "autonomous",
        "authority": {
            "can_read_production_telemetry": True,
            "can_create_tickets": True,
            "can_write_code": False,
            "can_review": False,
            "can_merge": False,
            "can_deploy": False,
            "can_page_humans": True,
            "can_change_business_rules": False,
            "must_escalate_when": ["severity_1", "customer_impact_over_500"],
        },
    },
]

TEAMMATE_AVATARS = {"tester": "🧪", "reviewer": "🔍", "implementer": "🛠️", "researcher": "📚", "docs": "📝"}
