// Generates src/avatars.ts at build time: DiceBear SVG data URIs, no runtime CDN.
// Agents: bottts-neutral robots seeded by handle on the agent's colour. Humans: notionists.
import { writeFileSync } from "node:fs";
import { createAvatar } from "@dicebear/core";
import { botttsNeutral, notionists } from "@dicebear/collection";

const AGENTS = {
  scout: "#f59e0b",
  forge: "#3b82f6",
  sentinel: "#a855f7",
  conductor: "#10b981",
  watchtower: "#ef4444",
  "mission-control": "#64748b",
};
const HUMANS = { maroun: "#f5b942", priya: "#ec4899", tom: "#22c55e", alex: "#a78bfa" };
const TEAMMATES = { tester: "#e879f9", reviewer: "#e879f9", implementer: "#e879f9", researcher: "#e879f9", docs: "#e879f9" };

const out = {};
for (const [handle, color] of Object.entries(AGENTS)) {
  out[handle] = createAvatar(botttsNeutral, { seed: handle, backgroundColor: [color.slice(1)], radius: 50, size: 128 }).toDataUri();
}
for (const [handle, color] of Object.entries(TEAMMATES)) {
  out[`teammate:${handle}`] = createAvatar(botttsNeutral, { seed: `teammate-${handle}`, backgroundColor: [color.slice(1)], radius: 50, size: 128 }).toDataUri();
}
for (const [handle, color] of Object.entries(HUMANS)) {
  out[handle] = createAvatar(notionists, { seed: handle, backgroundColor: [color.slice(1)], radius: 50, size: 128 }).toDataUri();
}
const lines = [
  "// GENERATED by scripts/gen-avatars.mjs — do not edit. DiceBear bottts-neutral (agents) and notionists (humans).",
  "export const AVATARS: Record<string, string> = {",
  ...Object.entries(out).map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`),
  "};",
  "",
];
writeFileSync(new URL("../src/avatars.ts", import.meta.url), lines.join("\n"));
console.log(`avatars.ts: ${Object.keys(out).length} avatars`);
